apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: cvo-policy
  namespace: infra-lifecycle
  annotations:
    policy.mcm.ibm.com/standards: NIST-CSF
    policy.mcm.ibm.com/categories: PR.IP Information Protection Processes and Procedures
    policy.mcm.ibm.com/controls: PR.IP-1 Baseline configuration
spec:
  complianceType: musthave
  remediationAction: enforce
  disabled: false
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: config.openshift.io/v1
        kind: ClusterVersion
        metadata:
          name: version
        spec:
          channel: stable-4.4
          upstream: https://api.openshift.com/api/upgrades_info/v1/graph
