apiVersion: multicloud.ibm.com/v1beta1
kind: Endpoint
metadata:
  creationTimestamp: null
  name: endpoint
  namespace: multicluster-endpoint
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  cisController:
    enabled: false
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  clusterName: spokecluster
  clusterNamespace: spokecluster
  connectionManager: {}
  iamPolicyController:
    enabled: true
  imagePullSecret: multiclusterhub-operator-pull-secret
  imageRegistry: quay.io/open-cluster-management
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  serviceRegistry:
    dnsSuffix: mcm.svc
    enabled: true
    plugins: kube-service
  version: 1.0.0
status: {}
